#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define MAX_MEMORYBUFFER_DEPTH 4
#define MAX_ERRORBUFFER_DEPTH 50
#define MAX_WIDTH 640
#define MAX_HEIGHT 512

#endif // CONSTANTS_H_INCLUDED
